# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        args:
        -   --line-length=96


-   repo: https://github.com/djlint/djLint
    rev: v1.34.1
    hooks:
    -   id: djlint-reformat
        args:
        -   --format-js
        -   --format-css
        -   --indent=2
        -   --indent-js=2
        -   --indent-css=2
