from dataclasses import dataclass
from datetime import datetime, timezone


@dataclass
class Changelog:
    """
    Data required to create new `Changelog`:
    - `changelog_uid` -> should be generated by `changelog_uid_generator.generate_changelog_uid()`
    - `author`
    - `title`
    - `date`
    - `category`
    - `content`
    - `tags`

    Optional data:
    - `link`
    - `link_description`

    Fields that are automatically generated:
    - `created_at`
    - `last_updated`
    - `archived`
    """

    changelog_uid: str
    author: str
    title: str
    date: datetime
    category: str
    content: str
    tags: list[str]
    link: str = ""
    link_description: str = ""
    created_at: datetime = datetime.now(timezone.utc)
    last_updated: datetime = datetime.now(timezone.utc)
    archived: bool = False
