from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Tuple


@dataclass
class ProjectInfo:
    """
    Data required to create a new `ProjectInfo`:
    - `project_uid` -> should be generated by `project_uid_generator.generate_project_uid()`
    - `author`
    - `title`
    - `short_description`
    - `tags`
    - `images` -> at least one image is required

    Optional data:
    - `custom_slug`

    Fields that are automatically generated:
    - `created_at`
    - `last_updated`
    - `archived`
    - `views`
    - `reads`
    """

    project_uid: str
    author: str
    title: str
    short_description: str
    tags: list[str]
    images: list[Tuple[str, str]]
    custom_slug: str
    created_at: datetime = datetime.now(timezone.utc)
    last_updated: datetime = datetime.now(timezone.utc)
    archived: bool = False
    views: int = 0
    reads: int = 0


@dataclass
class ProjectContent:
    """
    Data required to create a new `ProjectContent`:
    - `project_uid` -> should be generated by `project_uid_generator.generate_project_uid()`
    - `author`
    - `content`
    """

    project_uid: str
    author: str
    content: str
